/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anaco
 */
public class jMenu extends javax.swing.JFrame {

    /**
     * Creates new form jMenu
     */
    public jMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Agregar_Empleado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Txt_Nombre_Agregar_Empleado = new javax.swing.JTextField();
        Txt_Apellido_Agregar_Empleado = new javax.swing.JTextField();
        Txt_Nacimiento_Agregar_Empleado = new javax.swing.JTextField();
        Txt_Nif_Agregar_Empleado = new javax.swing.JTextField();
        btn_Agregar_Agregar_Empleado = new javax.swing.JButton();
        btn_Cancelar_Agregar_Proyecto = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        menu_Agregar = new javax.swing.JMenu();
        menuItem_Agregar_Empleado = new javax.swing.JMenuItem();
        menuItem_Agregar_Proyecto = new javax.swing.JMenuItem();
        menu_Modificar = new javax.swing.JMenu();
        menu_Asociar = new javax.swing.JMenu();
        menu_Consultar = new javax.swing.JMenu();
        menu_Gestión = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel_Agregar_Empleado.setVisible(false);
        panel_Agregar_Empleado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Agregar - Empleado");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Año nacimiento:");

        jLabel5.setText("NIF:");

        btn_Agregar_Agregar_Empleado.setText("Agregar");

        btn_Cancelar_Agregar_Proyecto.setText("Cancelar");

        javax.swing.GroupLayout panel_Agregar_EmpleadoLayout = new javax.swing.GroupLayout(panel_Agregar_Empleado);
        panel_Agregar_Empleado.setLayout(panel_Agregar_EmpleadoLayout);
        panel_Agregar_EmpleadoLayout.setHorizontalGroup(
            panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Agregar_EmpleadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Agregar_Agregar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btn_Cancelar_Agregar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(panel_Agregar_EmpleadoLayout.createSequentialGroup()
                .addGroup(panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_Agregar_EmpleadoLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panel_Agregar_EmpleadoLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Txt_Nombre_Agregar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel_Agregar_EmpleadoLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Txt_Apellido_Agregar_Empleado))
                                .addGroup(panel_Agregar_EmpleadoLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Txt_Nacimiento_Agregar_Empleado)))
                            .addGroup(panel_Agregar_EmpleadoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txt_Nif_Agregar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel_Agregar_EmpleadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        panel_Agregar_EmpleadoLayout.setVerticalGroup(
            panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Agregar_EmpleadoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_Nombre_Agregar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_Apellido_Agregar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Txt_Nacimiento_Agregar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Txt_Nif_Agregar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Agregar_Agregar_Empleado)
                    .addComponent(btn_Cancelar_Agregar_Proyecto))
                .addContainerGap())
        );

        menu_Agregar.setText("Agregar");

        menuItem_Agregar_Empleado.setText("Empleado");
        menuItem_Agregar_Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_Agregar_EmpleadoActionPerformed(evt);
            }
        });
        menu_Agregar.add(menuItem_Agregar_Empleado);

        menuItem_Agregar_Proyecto.setText("Proyecto");
        menu_Agregar.add(menuItem_Agregar_Proyecto);

        jMenuBar.add(menu_Agregar);

        menu_Modificar.setText("Modificar");
        jMenuBar.add(menu_Modificar);

        menu_Asociar.setText("Asociar");
        jMenuBar.add(menu_Asociar);

        menu_Consultar.setText("Consultar");
        jMenuBar.add(menu_Consultar);

        menu_Gestión.setText("Gestión");
        jMenuBar.add(menu_Gestión);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_Agregar_Empleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_Agregar_Empleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_Agregar_EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_Agregar_EmpleadoActionPerformed
        // TODO add your handling code here:
        panel_Agregar_Empleado.setVisible(true);
    }//GEN-LAST:event_menuItem_Agregar_EmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new jMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txt_Apellido_Agregar_Empleado;
    private javax.swing.JTextField Txt_Apellido_Agregar_Empleado1;
    private javax.swing.JTextField Txt_Apellido_Agregar_Empleado2;
    private javax.swing.JTextField Txt_Apellido_Agregar_Empleado3;
    private javax.swing.JTextField Txt_Nacimiento_Agregar_Empleado;
    private javax.swing.JTextField Txt_Nacimiento_Agregar_Empleado1;
    private javax.swing.JTextField Txt_Nacimiento_Agregar_Empleado2;
    private javax.swing.JTextField Txt_Nacimiento_Agregar_Empleado3;
    private javax.swing.JTextField Txt_Nif_Agregar_Empleado;
    private javax.swing.JTextField Txt_Nif_Agregar_Empleado1;
    private javax.swing.JTextField Txt_Nif_Agregar_Empleado2;
    private javax.swing.JTextField Txt_Nif_Agregar_Empleado3;
    private javax.swing.JTextField Txt_Nombre_Agregar_Empleado;
    private javax.swing.JTextField Txt_Nombre_Agregar_Empleado1;
    private javax.swing.JTextField Txt_Nombre_Agregar_Empleado2;
    private javax.swing.JTextField Txt_Nombre_Agregar_Empleado3;
    private javax.swing.JButton btn_Agregar_Agregar_Empleado;
    private javax.swing.JButton btn_Agregar_Agregar_Empleado1;
    private javax.swing.JButton btn_Agregar_Agregar_Empleado2;
    private javax.swing.JButton btn_Agregar_Agregar_Empleado3;
    private javax.swing.JButton btn_Cancelar_Agregar_Proyecto;
    private javax.swing.JButton btn_Cancelar_Agregar_Proyecto1;
    private javax.swing.JButton btn_Cancelar_Agregar_Proyecto2;
    private javax.swing.JButton btn_Cancelar_Agregar_Proyecto3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem menuItem_Agregar_Empleado;
    private javax.swing.JMenuItem menuItem_Agregar_Proyecto;
    private javax.swing.JMenu menu_Agregar;
    private javax.swing.JMenu menu_Asociar;
    private javax.swing.JMenu menu_Consultar;
    private javax.swing.JMenu menu_Gestión;
    private javax.swing.JMenu menu_Modificar;
    private javax.swing.JPanel panel_Agregar_Empleado;
    private javax.swing.JPanel panel_Agregar_Empleado1;
    private javax.swing.JPanel panel_Agregar_Empleado2;
    private javax.swing.JPanel panel_Agregar_Empleado3;
    // End of variables declaration//GEN-END:variables
}
