package vista;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anaco
 */
public class Interfaz_Admin extends javax.swing.JFrame {

    /**
     * Creates new form jMenu
     */
    public Interfaz_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_Test = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panel_Agregar_Empleado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Txt_Nombre_Agregar_Empleado = new javax.swing.JTextField();
        Txt_Apellido_Agregar_Empleado = new javax.swing.JTextField();
        Txt_Nacimiento_Agregar_Empleado = new javax.swing.JTextField();
        Txt_Nif_Agregar_Empleado = new javax.swing.JTextField();
        btn_Agregar_Agregar_Empleado = new javax.swing.JButton();
        btn_Cancelar_Agregar_Empleado = new javax.swing.JButton();
        panel_Agregar_Proyecto = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Txt_Titulo_Agregar_Proyecto = new javax.swing.JTextField();
        Txt_FechaInicio_Agregar_Proyecto = new javax.swing.JTextField();
        Txt_FechaFin_Agregar_Proyecto = new javax.swing.JTextField();
        Txt_Descripcion_Agregar_Proyecto = new javax.swing.JTextField();
        btn_Agregar_Agregar_Proyecto = new javax.swing.JButton();
        btn_Cancelar_Agregar_Proyecto = new javax.swing.JButton();
        panel_Modificar_Empleado = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_Modificar_Empleado = new javax.swing.JTable();
        txt_FiltrarNombre_Modificar_Empleado = new javax.swing.JTextField();
        txt_FiltrarApellido_Modificar_Empleado = new javax.swing.JTextField();
        txt_FiltrarNacimiento_Modificar_Empleado = new javax.swing.JTextField();
        txt_FiltrarNIF_Modificar_Empleado = new javax.swing.JTextField();
        btn_Filtrar_Modificar_Empleado = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_Modificar_Modificar_Empleado = new javax.swing.JButton();
        btn_Cancelar_Modificar_Empleado = new javax.swing.JButton();
        txt_Nombre_Modificar_Empleado = new javax.swing.JTextField();
        txt_Apellido_Modificar_Empleado = new javax.swing.JTextField();
        txt_Nacimiento_Modificar_Empleado = new javax.swing.JTextField();
        panel_Modificar_Proyecto = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_Modificar_Empleado1 = new javax.swing.JTable();
        txt_FiltrarTitulo_Modificar_Proyecto = new javax.swing.JTextField();
        txt_FiltrarFechaInicio_Modificar_Proyecto = new javax.swing.JTextField();
        txt_FiltrarFechaFin_Modificar_Proyecto = new javax.swing.JTextField();
        txt_FiltrarId_Modificar_Proyecto = new javax.swing.JTextField();
        txt_FiltrarDescripcion_Modificar_Proyecto = new javax.swing.JTextField();
        btn_Filtrar_Modificar_Proyecto = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btn_Modificar_Modificar_Proyecto = new javax.swing.JButton();
        btn_Cancelar_Modificar_Proyecto = new javax.swing.JButton();
        txt_Titulo_Modificar_Proyecto = new javax.swing.JTextField();
        txt_FechaInicio_Modificar_Proyecto = new javax.swing.JTextField();
        txt_FechaFin_Modificar_Proyecto = new javax.swing.JTextField();
        btn_ModificarDescripcion_Modificar_Proyecto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        menu_Agregar = new javax.swing.JMenu();
        menuItem_Agregar_Empleado = new javax.swing.JMenuItem();
        menuItem_Agregar_Proyecto = new javax.swing.JMenuItem();
        menu_Modificar = new javax.swing.JMenu();
        menuItem_Modificar_Empleado = new javax.swing.JMenuItem();
        menuItem_Modificar_Proyecto = new javax.swing.JMenuItem();
        menu_Asociar = new javax.swing.JMenu();
        menu_Consultar = new javax.swing.JMenu();
        menu_Gestión = new javax.swing.JMenu();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout menu_TestLayout = new javax.swing.GroupLayout(menu_Test);
        menu_Test.setLayout(menu_TestLayout);
        menu_TestLayout.setHorizontalGroup(
            menu_TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_TestLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(23, 23, 23))
            .addGroup(menu_TestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu_TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_TestLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(34, 34, 34)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menu_TestLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menu_TestLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        menu_TestLayout.setVerticalGroup(
            menu_TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_TestLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(menu_TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(menu_TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(menu_TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_TestLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_TestLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(menu_TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        panel_Agregar_Empleado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Agregar - Empleado");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Año nacimiento:");

        jLabel5.setText("NIF:");

        btn_Agregar_Agregar_Empleado.setText("Agregar");

        btn_Cancelar_Agregar_Empleado.setText("Cancelar");

        javax.swing.GroupLayout panel_Agregar_EmpleadoLayout = new javax.swing.GroupLayout(panel_Agregar_Empleado);
        panel_Agregar_Empleado.setLayout(panel_Agregar_EmpleadoLayout);
        panel_Agregar_EmpleadoLayout.setHorizontalGroup(
            panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Agregar_EmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Agregar_EmpleadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Agregar_Agregar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btn_Cancelar_Agregar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Agregar_EmpleadoLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_Agregar_EmpleadoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txt_Nacimiento_Agregar_Empleado))
                    .addGroup(panel_Agregar_EmpleadoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txt_Nif_Agregar_Empleado))
                    .addGroup(panel_Agregar_EmpleadoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txt_Nombre_Agregar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_Agregar_EmpleadoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txt_Apellido_Agregar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        panel_Agregar_EmpleadoLayout.setVerticalGroup(
            panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Agregar_EmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_Nombre_Agregar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_Apellido_Agregar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Txt_Nacimiento_Agregar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Txt_Nif_Agregar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(panel_Agregar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Agregar_Agregar_Empleado)
                    .addComponent(btn_Cancelar_Agregar_Empleado))
                .addGap(21, 21, 21))
        );

        jLayeredPane1.add(panel_Agregar_Empleado, "card3");

        panel_Agregar_Proyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Agregar - Proyecto");

        jLabel10.setText("Título:");

        jLabel11.setText("Fecha inicio:");

        jLabel12.setText("Fecha fin:");

        jLabel13.setText("Descripción:");

        btn_Agregar_Agregar_Proyecto.setText("Agregar");

        btn_Cancelar_Agregar_Proyecto.setText("Cancelar");

        javax.swing.GroupLayout panel_Agregar_ProyectoLayout = new javax.swing.GroupLayout(panel_Agregar_Proyecto);
        panel_Agregar_Proyecto.setLayout(panel_Agregar_ProyectoLayout);
        panel_Agregar_ProyectoLayout.setHorizontalGroup(
            panel_Agregar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Agregar_ProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Agregar_ProyectoLayout.createSequentialGroup()
                .addGap(0, 254, Short.MAX_VALUE)
                .addComponent(btn_Agregar_Agregar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btn_Cancelar_Agregar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Agregar_ProyectoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_Agregar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_Agregar_ProyectoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txt_Titulo_Agregar_Proyecto))
                    .addGroup(panel_Agregar_ProyectoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txt_Descripcion_Agregar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_Agregar_ProyectoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txt_FechaFin_Agregar_Proyecto))
                    .addGroup(panel_Agregar_ProyectoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txt_FechaInicio_Agregar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        panel_Agregar_ProyectoLayout.setVerticalGroup(
            panel_Agregar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Agregar_ProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(30, 30, 30)
                .addGroup(panel_Agregar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Txt_Titulo_Agregar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_Agregar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Txt_FechaInicio_Agregar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_Agregar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Txt_FechaFin_Agregar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_Agregar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_Agregar_ProyectoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addComponent(Txt_Descripcion_Agregar_Proyecto))
                .addGap(18, 18, 18)
                .addGroup(panel_Agregar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Agregar_Agregar_Proyecto)
                    .addComponent(btn_Cancelar_Agregar_Proyecto))
                .addGap(21, 21, 21))
        );

        jLayeredPane1.add(panel_Agregar_Proyecto, "card3");

        tabla_Modificar_Empleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla_Modificar_Empleado);

        txt_FiltrarNombre_Modificar_Empleado.setText("nombre");

        txt_FiltrarApellido_Modificar_Empleado.setText("apellido");

        txt_FiltrarNacimiento_Modificar_Empleado.setText("ano_nacimiento");

        txt_FiltrarNIF_Modificar_Empleado.setText("NIF");

        btn_Filtrar_Modificar_Empleado.setText("Filtrar");

        jLabel14.setText("Nombre:");

        jLabel15.setText("Apellido:");

        jLabel16.setText("Año Nacimiento:");

        btn_Modificar_Modificar_Empleado.setText("Modificar");
        btn_Modificar_Modificar_Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Modificar_Modificar_EmpleadoActionPerformed(evt);
            }
        });

        btn_Cancelar_Modificar_Empleado.setText("Cancelar");

        javax.swing.GroupLayout panel_Modificar_EmpleadoLayout = new javax.swing.GroupLayout(panel_Modificar_Empleado);
        panel_Modificar_Empleado.setLayout(panel_Modificar_EmpleadoLayout);
        panel_Modificar_EmpleadoLayout.setHorizontalGroup(
            panel_Modificar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel_Modificar_EmpleadoLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(btn_Filtrar_Modificar_Empleado)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel_Modificar_EmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Modificar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_Modificar_EmpleadoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panel_Modificar_EmpleadoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txt_FiltrarNombre_Modificar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_FiltrarApellido_Modificar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_FiltrarNacimiento_Modificar_Empleado)
                        .addGap(18, 18, 18)
                        .addComponent(txt_FiltrarNIF_Modificar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(panel_Modificar_EmpleadoLayout.createSequentialGroup()
                        .addGroup(panel_Modificar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panel_Modificar_EmpleadoLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Apellido_Modificar_Empleado))
                            .addGroup(panel_Modificar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Modificar_EmpleadoLayout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_Nacimiento_Modificar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel_Modificar_EmpleadoLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_Nombre_Modificar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_Modificar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Modificar_Modificar_Empleado)
                            .addComponent(btn_Cancelar_Modificar_Empleado, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        panel_Modificar_EmpleadoLayout.setVerticalGroup(
            panel_Modificar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Modificar_EmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_Modificar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_FiltrarNombre_Modificar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_FiltrarApellido_Modificar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_FiltrarNacimiento_Modificar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_FiltrarNIF_Modificar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Filtrar_Modificar_Empleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_Modificar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_Modificar_EmpleadoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_Modificar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_Nombre_Modificar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_Modificar_EmpleadoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_Modificar_Modificar_Empleado)))
                .addGroup(panel_Modificar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_Modificar_EmpleadoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_Modificar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt_Apellido_Modificar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_Modificar_EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txt_Nacimiento_Modificar_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_Modificar_EmpleadoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btn_Cancelar_Modificar_Empleado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panel_Modificar_Empleado, "card3");

        tabla_Modificar_Empleado1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabla_Modificar_Empleado1);

        txt_FiltrarTitulo_Modificar_Proyecto.setText("título");
        txt_FiltrarTitulo_Modificar_Proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FiltrarTitulo_Modificar_ProyectoActionPerformed(evt);
            }
        });

        txt_FiltrarFechaInicio_Modificar_Proyecto.setText("fecha inicio");

        txt_FiltrarFechaFin_Modificar_Proyecto.setText("fecha fin");

        txt_FiltrarId_Modificar_Proyecto.setText("id proyecto");

        txt_FiltrarDescripcion_Modificar_Proyecto.setText("contenido descripción");

        btn_Filtrar_Modificar_Proyecto.setText("Filtrar");

        jLabel17.setText("Título:");

        jLabel18.setText("fecha inicio:");

        jLabel19.setText("fecha fin:");

        btn_Modificar_Modificar_Proyecto.setText("Modificar");
        btn_Modificar_Modificar_Proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Modificar_Modificar_ProyectoActionPerformed(evt);
            }
        });

        btn_Cancelar_Modificar_Proyecto.setText("Cancelar");

        btn_ModificarDescripcion_Modificar_Proyecto.setText("<html>Modificar<br>descripcion</html>");

        javax.swing.GroupLayout panel_Modificar_ProyectoLayout = new javax.swing.GroupLayout(panel_Modificar_Proyecto);
        panel_Modificar_Proyecto.setLayout(panel_Modificar_ProyectoLayout);
        panel_Modificar_ProyectoLayout.setHorizontalGroup(
            panel_Modificar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel_Modificar_ProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Modificar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_Modificar_ProyectoLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panel_Modificar_ProyectoLayout.createSequentialGroup()
                        .addGroup(panel_Modificar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_Modificar_ProyectoLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_FechaFin_Modificar_Proyecto))
                            .addGroup(panel_Modificar_ProyectoLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_FechaInicio_Modificar_Proyecto))
                            .addGroup(panel_Modificar_ProyectoLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Titulo_Modificar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 28, Short.MAX_VALUE)
                        .addComponent(btn_ModificarDescripcion_Modificar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panel_Modificar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Modificar_Modificar_Proyecto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Cancelar_Modificar_Proyecto, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Modificar_ProyectoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panel_Modificar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_Modificar_ProyectoLayout.createSequentialGroup()
                                .addComponent(txt_FiltrarTitulo_Modificar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_FiltrarFechaInicio_Modificar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_FiltrarFechaFin_Modificar_Proyecto))
                            .addComponent(txt_FiltrarDescripcion_Modificar_Proyecto))
                        .addGap(18, 18, 18)
                        .addGroup(panel_Modificar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_FiltrarId_Modificar_Proyecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Filtrar_Modificar_Proyecto, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20))))
        );
        panel_Modificar_ProyectoLayout.setVerticalGroup(
            panel_Modificar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Modificar_ProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_Modificar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_FiltrarTitulo_Modificar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_FiltrarFechaInicio_Modificar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_FiltrarFechaFin_Modificar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_FiltrarId_Modificar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_Modificar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Filtrar_Modificar_Proyecto)
                    .addComponent(txt_FiltrarDescripcion_Modificar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_Modificar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_Modificar_ProyectoLayout.createSequentialGroup()
                        .addGroup(panel_Modificar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_Modificar_ProyectoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_Modificar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txt_Titulo_Modificar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_Modificar_ProyectoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btn_Modificar_Modificar_Proyecto)))
                        .addGroup(panel_Modificar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_Modificar_ProyectoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_Modificar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(txt_FechaInicio_Modificar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panel_Modificar_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(txt_FechaFin_Modificar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Modificar_ProyectoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Cancelar_Modificar_Proyecto)
                                .addGap(21, 21, 21))))
                    .addGroup(panel_Modificar_ProyectoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_ModificarDescripcion_Modificar_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panel_Modificar_Proyecto, "card3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jLayeredPane1.add(jPanel3, "card3");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jLayeredPane1.add(jPanel4, "card3");

        menu_Agregar.setText("Agregar");

        menuItem_Agregar_Empleado.setText("Empleado");
        menuItem_Agregar_Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_Agregar_EmpleadoActionPerformed(evt);
            }
        });
        menu_Agregar.add(menuItem_Agregar_Empleado);

        menuItem_Agregar_Proyecto.setText("Proyecto");
        menuItem_Agregar_Proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_Agregar_ProyectoActionPerformed(evt);
            }
        });
        menu_Agregar.add(menuItem_Agregar_Proyecto);

        jMenuBar.add(menu_Agregar);

        menu_Modificar.setText("Modificar");

        menuItem_Modificar_Empleado.setText("Empleado");
        menu_Modificar.add(menuItem_Modificar_Empleado);

        menuItem_Modificar_Proyecto.setText("Proyecto");
        menu_Modificar.add(menuItem_Modificar_Proyecto);

        jMenuBar.add(menu_Modificar);

        menu_Asociar.setText("Asociar");
        jMenuBar.add(menu_Asociar);

        menu_Consultar.setText("Consultar");
        jMenuBar.add(menu_Consultar);

        menu_Gestión.setText("Gestión");
        jMenuBar.add(menu_Gestión);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_Agregar_EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_Agregar_EmpleadoActionPerformed
        // TODO add your handling code here:
        //panel_Agregar_Empleado.setVisible(true);
    }//GEN-LAST:event_menuItem_Agregar_EmpleadoActionPerformed
    
    private void menuItem_Agregar_ProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_Agregar_ProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem_Agregar_ProyectoActionPerformed

    private void btn_Modificar_Modificar_EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Modificar_Modificar_EmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Modificar_Modificar_EmpleadoActionPerformed

    private void btn_Modificar_Modificar_ProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Modificar_Modificar_ProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Modificar_Modificar_ProyectoActionPerformed

    private void txt_FiltrarTitulo_Modificar_ProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FiltrarTitulo_Modificar_ProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FiltrarTitulo_Modificar_ProyectoActionPerformed

    /*private void switchPanels (JPanel panel){
        jLayeredPane1.removeAll();
        jLayeredPane1.add(panel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Interfaz_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txt_Apellido_Agregar_Empleado;
    private javax.swing.JTextField Txt_Descripcion_Agregar_Proyecto;
    private javax.swing.JTextField Txt_FechaFin_Agregar_Proyecto;
    private javax.swing.JTextField Txt_FechaInicio_Agregar_Proyecto;
    private javax.swing.JTextField Txt_Nacimiento_Agregar_Empleado;
    private javax.swing.JTextField Txt_Nif_Agregar_Empleado;
    private javax.swing.JTextField Txt_Nombre_Agregar_Empleado;
    private javax.swing.JTextField Txt_Titulo_Agregar_Proyecto;
    private javax.swing.JButton btn_Agregar_Agregar_Empleado;
    public javax.swing.JButton btn_Agregar_Agregar_Proyecto;
    private javax.swing.JButton btn_Cancelar_Agregar_Empleado;
    private javax.swing.JButton btn_Cancelar_Agregar_Proyecto;
    private javax.swing.JButton btn_Cancelar_Modificar_Empleado;
    private javax.swing.JButton btn_Cancelar_Modificar_Proyecto;
    private javax.swing.JButton btn_Filtrar_Modificar_Empleado;
    private javax.swing.JButton btn_Filtrar_Modificar_Proyecto;
    private javax.swing.JButton btn_ModificarDescripcion_Modificar_Proyecto;
    private javax.swing.JButton btn_Modificar_Modificar_Empleado;
    private javax.swing.JButton btn_Modificar_Modificar_Proyecto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JMenuItem menuItem_Agregar_Empleado;
    public javax.swing.JMenuItem menuItem_Agregar_Proyecto;
    public javax.swing.JMenuItem menuItem_Modificar_Empleado;
    public javax.swing.JMenuItem menuItem_Modificar_Proyecto;
    private javax.swing.JMenu menu_Agregar;
    private javax.swing.JMenu menu_Asociar;
    private javax.swing.JMenu menu_Consultar;
    private javax.swing.JMenu menu_Gestión;
    private javax.swing.JMenu menu_Modificar;
    private javax.swing.JPanel menu_Test;
    public javax.swing.JPanel panel_Agregar_Empleado;
    public javax.swing.JPanel panel_Agregar_Proyecto;
    public javax.swing.JPanel panel_Modificar_Empleado;
    public javax.swing.JPanel panel_Modificar_Proyecto;
    private javax.swing.JTable tabla_Modificar_Empleado;
    private javax.swing.JTable tabla_Modificar_Empleado1;
    private javax.swing.JTextField txt_Apellido_Modificar_Empleado;
    private javax.swing.JTextField txt_FechaFin_Modificar_Proyecto;
    private javax.swing.JTextField txt_FechaInicio_Modificar_Proyecto;
    private javax.swing.JTextField txt_FiltrarApellido_Modificar_Empleado;
    private javax.swing.JTextField txt_FiltrarDescripcion_Modificar_Proyecto;
    private javax.swing.JTextField txt_FiltrarFechaFin_Modificar_Proyecto;
    private javax.swing.JTextField txt_FiltrarFechaInicio_Modificar_Proyecto;
    private javax.swing.JTextField txt_FiltrarId_Modificar_Proyecto;
    private javax.swing.JTextField txt_FiltrarNIF_Modificar_Empleado;
    private javax.swing.JTextField txt_FiltrarNacimiento_Modificar_Empleado;
    private javax.swing.JTextField txt_FiltrarNombre_Modificar_Empleado;
    private javax.swing.JTextField txt_FiltrarTitulo_Modificar_Proyecto;
    private javax.swing.JTextField txt_Nacimiento_Modificar_Empleado;
    private javax.swing.JTextField txt_Nombre_Modificar_Empleado;
    private javax.swing.JTextField txt_Titulo_Modificar_Proyecto;
    // End of variables declaration//GEN-END:variables
}
